"""Write VALIDATION_REPORT.md into scanned project folders."""

from __future__ import annotations

from pathlib import Path

from rmv.scan.discover import GRProject
from rmv.scan.readme_parser import ReadmeSummary, parse_readme
from rmv.scan.runner import ProjectValidationRun

REPORT_HEADER = """<!-- Generated by radio-modulation-validator. Do not edit manually. -->
<!-- This file is safe to commit to the project repository. -->
<!-- It contains no personal data and no sensitive information. -->

"""


def _overall_result(run: ProjectValidationRun) -> str:
    if run.hard_failed > 0:
        return "HARD FAIL"
    if run.soft_failed > 0:
        return "SOFT FAIL"
    if run.passed == 0 and run.skipped == run.total_blocks:
        return "SKIPPED"
    return "PASS"


def _result_emoji(row: dict[str, object]) -> str:
    if row.get("skipped"):
        return "-"
    if row.get("hard_fail"):
        return "FAIL"
    if row.get("family_pass") and row.get("order_pass"):
        return "PASS"
    return "WARN"


def write_project_report(
    project: GRProject,
    run: ProjectValidationRun,
    output_path: Path,
    *,
    summary: ReadmeSummary | None = None,
) -> None:
    """Write markdown validation report (does not modify project source)."""
    if summary is None and project.readme_path is not None:
        summary = parse_readme(project.readme_path)
    ai_yes = summary.is_ai_generated if summary else False
    ai_notice = summary.ai_notice if summary else ""

    lines = [
        REPORT_HEADER,
        f"# Validation Report — {project.name}",
        "",
        f"Generated by radio-modulation-validator on {run.run_at}",
        f"GNU Radio version: {project.gr_version}",
        f"AI-generated code: {'yes' if ai_yes else 'no'}",
    ]
    if ai_notice:
        lines.append(f"> {ai_notice[:500].replace(chr(10), ' ')}")
    lines.extend(
        [
            "",
            "## Summary",
            "",
            "| Metric | Value |",
            "|---|---|",
            f"| Blocks validated | {run.passed + run.soft_failed + run.hard_failed} |",
            f"| Passed | {run.passed} |",
            f"| Soft failed | {run.soft_failed} |",
            f"| Hard failed | {run.hard_failed} |",
            f"| Skipped | {run.skipped} |",
            f"| Overall result | {_overall_result(run)} |",
            "",
            "## Results by block",
            "",
            "| Block | Expected family | Expected order | Predicted family | "
            "Predicted order | F-conf | O-conf | Result |",
            "|---|---|---|---|---|---|---|---|",
        ]
    )

    for row in run.block_results:
        if row.get("skipped"):
            lines.append(
                f"| {row.get('block', '')} | - | - | - | - | - | - | skipped |"
            )
            continue
        emoji = _result_emoji(row)
        lines.append(
            f"| {row['block']} | {row['expected_family']} | {row['expected_order']} | "
            f"{row['predicted_family']} | {row['predicted_order']} | "
            f"{float(row['family_confidence']):.2f} | {float(row['order_confidence']):.2f} | {emoji} |"
        )

    lines.extend(["", "## Issues", ""])
    if run.issues:
        for issue in run.issues:
            lines.append(f"- **{issue.severity}** ({issue.block_name or 'project'}): {issue.description}")
    else:
        lines.append("No issues recorded.")

    lines.extend(["", "## Skipped blocks", ""])
    skipped_rows = [r for r in run.block_results if r.get("skipped")]
    if skipped_rows:
        for row in skipped_rows:
            lines.append(f"- **{row.get('block')}**: {row.get('reason', 'skipped')}")
    else:
        lines.append("None.")

    lines.extend(
        [
            "",
            "## Validation methodology",
            "",
            "IQ samples were generated using GNU Radio built-in blocks and numpy/scipy only.",
            "The project's own blocks were NOT used to generate reference data.",
            "This validation checks whether waveforms match expected modulation families and",
            "orders using ONNX classifiers trained on public RF datasets.",
            "",
            "## Notes",
            "",
            "- Underlying modulation validated only for: DMR, M17, YSF, D-Star (GMSK), "
            "GMSK, NXDN, dPMR, P25",
            "- Protocol framing and FEC not verified",
            "- For gr-sleipnir: 8-carrier QPSK validated using custom plugin "
            "(carrier count, spacing, symbol rate, QPSK constellation checks)",
            "",
            "### Excluded from validation (by design)",
            "",
            "- Spread spectrum (DSSS, GDSS): designed to appear as noise; classifier "
            "output is not meaningful",
            "- Cryptography modules (gr-nacl, gr-openssl, gr-linux-crypto): no RF "
            "modulation to validate",
            "- Audio codecs (e.g. gr-opus): no RF modulation produced",
            "- GNU Radio framework source trees (gnuradio, gnuradio4, gnuradio3): "
            "not OOT modules",
            "",
        ]
    )

    output_path.write_text("\n".join(lines), encoding="utf-8")
